# Generated by Django 5.1.4 on 2024-12-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Customers',
        ),
    ]
