# Generated by Django 5.1.4 on 2024-12-14 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
